### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by Squidious** [Pale-Moon-Addons-Team/adblock-latitude#19] opened 2015-11-22 16:42 UTC
Windows 7 and Pale Moon 25.8.0 (x64)

Going to this URL: http://www.healthline.com/health/migraine/severe-acute-migraines-vertigo-nausea#2

Causes an infinite loop where the same HTML elements are reproduced over and over on the screen until the scroll bar is pegged, CPU is pegged (for that process), Pale Moon becomes unresponsive.  Is reproducible, will happen every time I open that page unless I hit the Stop Loading button before it gets to the point where it is unresponsive.  Disabling AdBlock Latitude makes the problem go away.

There are other pages that exhibit this same problem.

**Comment by mattatobin** [comment] 2015-11-22 18:16
I can confirm this. What other pages present the issue.

However, there isn't a real way I can debug this since the thing seems to lock up before I can do anything to see what is happening.

**Comment by mattatobin** [comment] 2015-11-22 18:43
This "reloading action" isn't caused by ABL.. It happens regardless.. This site seems to throw a ridiculous amount of css and js at the browser plus aggressively seems to keep reloading specific elements.

This slows the browser down QUITE a bit because of all the ridiculous crap being thrown at it.. Add ABL that trys to filter all this and you have an endless amount of constant filtering and reevaluation of the page. No wonder the added weight is enough to drive the process over the edge.

I am calling this a flaw in this framework and website. Even without ABL the browser is struggling to deal with this insanity.

WONTFIX

**Comment by mattatobin** [comment] 2015-11-22 19:02
As an aside I loaded this up in Google Chrome with and without ABP.. You know.. For Science.

With ABP the process became so unresponsive it nearly killed the Chrome parent process. Also I saw the URL's html ancor seem to jump through 1 to 540 very quickly and died.. Then the host process came back and told me the page became unresponsive.

Without ABP in Chrome it does work.. but takes a while to stop it's constant loading of elements.

My guess is the scripting on this site framework simply expects the ad element to be there and when it isn't it simply can't cope and the scripts go crazy trying to deal with/fix the page.

So yeah this is most def a problem on the part of the site its self and not with a specific browser. Technically, adblock does break it but only in so far as the site's active scripting can't cope with a missing element.

**Comment by ikar-us** [comment] 2015-11-22 23:41
Result of some more tests:
Yandex (Chromium) with its Adguard extension becomes unresponsive, too.
Other Chromium browsers with built-in ABP even crash.
But Adguard for PM handles the page well.

**Comment by Squidious** [comment] 2015-11-22 23:41
I see this a couple of times a week and switch to chrome (without adblock) when it is something I actually want to read.  I will report here the next couple of times I see it.

**Comment by Squidious** [comment] 2015-12-14 17:34
Here is another one if you care to investigate:  http://www.attn.com/stories/4677/islamophobia-on-the-bus?utm_source=other98&utm_medium=fbpost&utm_campaign=influencer

**Closed** 2016-06-10 07:24 UTC
Labels: WONTFIX
